### ISSUE TITLE
[Question] Could I use this API to scan another pod?

### ISSUE THREAD

**Issue by Tom284** [benzino77/clamav-rest-api#10]
Hello, would it be possible to scan another pod in the cluster through this API?

Like for example with the [C# Kubernetes client](https://github.com/kubernetes-client/csharp)

**Comment by benzino77** [comment]
This is just a REST API, so you can call API endpoint with file you want to scan (HTTP POST) . You can call this API from other pods on your cluster. On the other hand this solution is not able to scan files directly, located in other pods - it can only scan files passed via REST call.

**Comment by Tom284** [comment]
Oke, thank you very much for responding!
