### ISSUE TITLE
TypeError: req.files.hasOwnProperty is not a function

### ISSUE THREAD

**Issue by xvisionbelgium** [benzino77/clamav-rest-api#44]
Environment : NodeJS v16.18.1 on CentOS 7

We are getting the error when postng a file. Any idea how to fix this ?

/home/xvision/node/clamav-rest-api/src/utils/checkParams.js:20
  const hasProperKey = req.files.hasOwnProperty(process.env.APP_FORM_KEY);

TypeError: req.files.hasOwnProperty is not a function
    at checkParams (/home/xvision/node/clamav-rest-api/src/utils/checkParams.js:20:34)
    at /home/xvision/node/clamav-rest-api/src/routes/scan.js:10:24
    at Layer.handle [as handle_request] (/home/xvision/node/clamav-rest-api/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/xvision/node/clamav-rest-api/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/xvision/node/clamav-rest-api/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/xvision/node/clamav-rest-api/node_modules/express/lib/router/layer.js:95:5)
    at /home/xvision/node/clamav-rest-api/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/home/xvision/node/clamav-rest-api/node_modules/express/lib/router/index.js:346:12)
    at next (/home/xvision/node/clamav-rest-api/node_modules/express/lib/router/index.js:280:10)
    at Function.handle (/home/xvision/node/clamav-rest-api/node_modules/express/lib/router/index.js:175:3)

**Comment by benzino77** [comment]
What is a value set for `APP_FORM_KEY` in your `.env` (or in your environemnt) and how do you make a POST call to CRA?

**Comment by benzino77** [comment]
Have you run `npm install` in your CRA directory as stated in the[ README](https://github.com/benzino77/clamav-rest-api#how-to-start-clamav-rest-api)?

**Comment by xvisionbelgium** [comment]
Yes, did the following
Cloned the repo
Npm install
Npm start

.env file is the following

NODE_ENV=production

APP_PORT=3000
APP_FORM_KEY=FILES
APP_MORGAN_LOG_FORMAT=combined
APP_MAX_FILE_SIZE=26214400
APP_MAX_FILES_NUMBER=4

CLAMD_IP=127.0.0.1
CLAMD_PORT=3310
CLAMD_TIMEOUT=30000
You can also start clamav-rest-api by cloning the repo and run commands listed below:
npm install
npm install -D # if you want to run tests or examples
# Configuration described below - needed before start app
npm start

**Comment by xvisionbelgium** [comment]
If I comment out the test in the code, the scanning works file

**Comment by benzino77** [comment]
Which line/lines do you comment out?

**Comment by xvisionbelgium** [comment]
Hi

APP_FORM_KEY is FILES as default
I’ve debugged (with console.write) the values and they seem correct

**Comment by benzino77** [comment]
How do you make a POST call to CRA?

**Comment by xvisionbelgium** [comment]
I‘m testing with Postman

***@***.***

**Comment by benzino77** [comment]
How do you set Postman "Body tab"

**Comment by xvisionbelgium** [comment]
Seems that my screenshot that I’ve added came not through…
Set up like described in your README.md

Screenshot : https://1drv.ms/u/s!AiMpBVIUzr5T33OmZ1pfAcvJGErK?e=AbaZE9

**Comment by xvisionbelgium** [comment]
If I dump req.files object ( console.write(req.files) )

req.files DUMP
---------------------------------------------------------------------------
[Object: null prototype] {
  FILES: {
    name: 'eicar.com',
    data: <Buffer 58 35 4f 21 50 25 40 41 50 5b 34 5c 50 5a 58 35 34 28 50 5e 29 37 43 43 29 37 7d 24 45 49 43 41 52 2d 53 54 41 4e 44 41 52 44 2d 41 4e 54 49 56 49 52 ... 18 more bytes>,
    size: 68,
    encoding: '7bit',
    tempFilePath: '',
    truncated: false,
    mimetype: 'application/x-msdownload',
    md5: '44d88612fea8a8f36de82e1278abb02f',
    mv: [Function: mv]
  }
}
--------------

**Comment by benzino77** [comment]
Hint: do not upgrade `express-filesupload` package.

**Comment by xvisionbelgium** [comment]
Tried it… same problem

**Comment by xvisionbelgium** [comment]
This seems to do the trick… forced it to v1.1.9
But now I got a extra vulnerability warning…

**Comment by benzino77** [comment]
If you are using CRA as it is, you don't have to "force" anything. That is what `package*.json` files are for. To install proper versions of libraries for a project.

**Comment by xvisionbelgium** [comment]
It breaks if express-fileupload is 1.3.0 or higher
1.2.1 works fine

**Comment by benzino77** [comment]
You can pull the latest version of CRA which is using latest `express-fileupload`.
