### ISSUE TITLE
Limited File Types

### ISSUE THREAD

**Issue by g7crservice-sajid-f** [benzino77/clamav-rest-api#51]
""is_infected": null" is for almost all types of file except text and gif. Am i missing any configuration

**Comment by benzino77** [comment]
Hi there,

It is probably related to https://github.com/benzino77/clamav-rest-api/issues/49

**Comment by benzino77** [comment]
Try to pull new CRA docker image and test your setup.

**Comment by g7crservice-sajid-f** [comment]
Thanks a lot @benzino77 . will take latest. For time being have implemented retry policy in scan that bypassed the current issue.
