### ISSUE TITLE
Error when calling /

### ISSUE THREAD

**Issue by phlegx** [benzino77/clamav-rest-api#56]
HI there, When calling the service with curl like:

`curl -s  clamav-api-service.clamav.svc.cluster.local:3000` 

I get back:

`{"success":false,"data":{"error":"Not allowed."}}`

Should't that give me the version? I mean the API is up and running.

https://github.com/benzino77/clamav-rest-api/blob/e10759250b3c9f2ab806d2760287da1df1702c22/src/routes/version.js#L28

Thanks
Martin

**Comment by benzino77** [comment]
Exactly. But maybe it is not the worst idea to add dedicated endpoints for readiness, etc.. I will have a look at this after I get back from my vacations.

**Comment by phlegx** [comment]
Hi @benzino77 yes for sure that would be nice to have! Let me know when it is implemented!
